# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jen Wibowo
email: jennifer.wibowo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! My name is Jen Wibowo. I like designing & most recently product managing things. Current life goal: Camp beautiful places.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jenwibowo.at" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  jenwibs
insta_username: jenwibs

# Project url
permalink: /work/:title/ 

# Build settings
markdown: kramdown
